---
# environment file for dgnest.nginx

- name: Create files ntp
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: _nginx_create_files
  when: _nginx_create_files is defined
