---
# task file for dgnest.nginx

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ _nginx.templates | default({}) }}"
  when: _nginx is defined


- name: enabled gzip
  template:
    src: "gzip.conf.j2"
    dest: "{{ _nginx_conf_path }}/gzip.conf"
  when: nginx_gzip is defined and nginx_gzip|bool
