---

# task file for dgnest.nginx

- name: Add PPA for Nginx.
  apt_repository:
    repo: 'ppa:nginx/{{ _nginx_ppa_version }}'
    state: present
    update_cache: true
  register: nginx_ppa_added
  when:
    - _nginx_ppa_version is defined

- name: Update apt cache.
  apt: update_cache=true cache_valid_time=86400
  changed_when: false

- name: Ensure nginx is installed.
  package:
    name: "{{ _nginx_package_name }}"
    state: latest